/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alumno
 */
public class ejerc_2_1 extends javax.swing.JFrame {

     DefaultTableModel model;
    int selectrow;
    int fila;
    
    public void TableModel()
    {
        this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
        this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
        this.jTable1.getColumnModel().getColumn(3).setPreferredWidth(200);     
        model = (DefaultTableModel)this.jTable1.getModel();
        model.setNumRows(0);
    }
    
    public void iniciar()
     
    {
        this.txtid.setText(null);
        this.txtid.setEnabled(false);
        this.txtnombre.setText(null);
        this.txtnombre.setEnabled(false);
        this.txtdireccion.setText(null);
        this.txtdireccion.setEnabled(false);
        this.txtcorreo.setText(null);
        this.txtcorreo.setEnabled(false);
        this.bagregar.setEnabled(false);
        this.bactualizar.setEnabled(false);
        this.beditar.setEnabled(false);
        this.beliminar.setEnabled(false);
        this.bcancelar.setEnabled(false);
        this.bnuevo.setEnabled(true);
        this.jTable1.setEnabled(true);
        fila=0;
    }
    
    public void cancelar()
    {
        iniciar();
        
    }
    
    public void nuevo()
    {
        iniciar();
        this.txtid.setText(String.valueOf(this.jTable1.getRowCount()+1));  
        this.txtnombre.setEnabled(true);
        this.txtcorreo.setEnabled(true);
        this.txtdireccion.setEnabled(true);
        this.bagregar.setEnabled(true);
    }
    
    public void agregar()
    {
       if(this.txtnombre.getText().isEmpty() ||this.txtcorreo.getText().isEmpty() || this.txtdireccion.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(null,"Ingrese los datos:");
       }
       else{
           model.addRow(new Object [] {this.txtid.getText() ,this.txtnombre.getText() , this.txtcorreo.getText(),this.txtdireccion.getText()});
           iniciar();
       }
    }
    
    public void obtenerfila()
    {
        if(this.jTable1.getRowCount()> 0 || this.bagregar.isEnabled()==false)
        {
           fila=this.jTable1.getSelectedRow();
           txtid.setText(String.valueOf(model.getValueAt(fila,0)));
           txtnombre.setText(String.valueOf(model.getValueAt(fila,1)));
           txtcorreo.setText(String.valueOf(model.getValueAt(fila,2)));
           txtdireccion.setText(String.valueOf(model.getValueAt(fila,3)));
           this.bnuevo.setEnabled(false);
           this.beditar.setEnabled(true);
           this.beliminar.setEnabled(true);
        }      
    }
    
    public void editar()
    {
        this.jTable1.setEnabled(false);
        this.bactualizar.setEnabled(true);
        this.bcancelar.setEnabled(false);
        this.beliminar.setEnabled(false);  //boton eliminar(false)
        this.txtnombre.setEnabled(true);
        this.txtcorreo.setEnabled(true);
        this.txtdireccion.setEnabled(true);
    }
    
    public void actualizar()
    {
        if(this.txtcorreo.getText().isEmpty() || this.txtnombre.getText().isEmpty()) //si esta vacio que me muestre el mensaje
        {
            JOptionPane.showMessageDialog(null,"Ingrese los datos");//mensahe
        }
        else
        {
            model.setValueAt(txtnombre.getText(), fila, 1);
            model.setValueAt(txtdireccion.getText(), fila, 2);
            model.setValueAt(txtcorreo.getText(), fila, 3);
            iniciar();
        }
    }
    
    public void eliminar()
    {
        int confirmacion = JOptionPane.showConfirmDialog(null,"eliminar fila","Mensaje del sistema",JOptionPane.YES_NO_OPTION);
        if(confirmacion==0)
        {
            model.removeRow(fila);
            reiniciar();
            iniciar();
        }
    }
    
    public void reiniciar()
    {
       for(int i=0;i<jTable1.getRowCount();i++)
       {
           model.setValueAt(i+1, i, 0);
       }
    }
    
    public ejerc_2_1() {
        initComponents();
        setLocationRelativeTo(null);
        iniciar();
        TableModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bactualizar = new javax.swing.JButton();
        beditar = new javax.swing.JButton();
        bnuevo = new javax.swing.JButton();
        bagregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bcancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        beliminar = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bactualizar.setText("Actualizar");
        bactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bactualizarActionPerformed(evt);
            }
        });

        beditar.setText("Editar");
        beditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditarActionPerformed(evt);
            }
        });

        bnuevo.setText("Nuevo");
        bnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnuevoActionPerformed(evt);
            }
        });

        bagregar.setText("Agregar");
        bagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagregarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NombreyApellido", "Direccion", "CorreoElectronico"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Nombre y Apellido");

        jLabel3.setText("Direccion");

        bcancelar.setText("Cancelar");
        bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("CorreoElectronico");

        beliminar.setText("Eliminar");
        beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliminarActionPerformed(evt);
            }
        });

        txtid.setEnabled(false);

        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtid)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnombre))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bnuevo)
                        .addGap(30, 30, 30)
                        .addComponent(bagregar)
                        .addGap(18, 18, 18)
                        .addComponent(bactualizar)
                        .addGap(18, 18, 18)
                        .addComponent(beditar)
                        .addGap(18, 18, 18)
                        .addComponent(bcancelar)
                        .addGap(29, 29, 29)
                        .addComponent(beliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnuevo)
                    .addComponent(bagregar)
                    .addComponent(bactualizar)
                    .addComponent(beditar)
                    .addComponent(bcancelar)
                    .addComponent(beliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bactualizarActionPerformed
        this.actualizar();// TODO add your handling code here:
    }//GEN-LAST:event_bactualizarActionPerformed

    private void beditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditarActionPerformed
        this.editar();        // TODO add your handling code here:
    }//GEN-LAST:event_beditarActionPerformed

    private void bnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnuevoActionPerformed
        this.nuevo();        // TODO add your handling code here:
    }//GEN-LAST:event_bnuevoActionPerformed

    private void bagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagregarActionPerformed
        this.agregar();        // TODO add your handling code here:
    }//GEN-LAST:event_bagregarActionPerformed

    private void bcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelarActionPerformed
        this.cancelar();        // TODO add your handling code here:
    }//GEN-LAST:event_bcancelarActionPerformed

    private void beliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliminarActionPerformed
        this.eliminar();// TODO add your handling code here:
    }//GEN-LAST:event_beliminarActionPerformed

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejerc_2_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejerc_2_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejerc_2_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejerc_2_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejerc_2_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bactualizar;
    private javax.swing.JButton bagregar;
    private javax.swing.JButton bcancelar;
    private javax.swing.JButton beditar;
    private javax.swing.JButton beliminar;
    private javax.swing.JButton bnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
